from init_database import db_session
from models import Answer

answ1  = Answer(1,3,"バイト")
answ2  = Answer(1,2,"勉強")
answ3  = Answer(1,1,"株")
answ4  = Answer(1,4,"趣味")
answ5  = Answer(2,1,"安定性を求めたから")
answ6  = Answer(2,4,"どこにも受からなかったから")
answ7  = Answer(2,3,"自分が成長できる環境だと思ったから")
answ8  = Answer(2,2,"経営理念に惹かれたから")
answ9  = Answer(3,4,"蓋が落ちないように")
answ10 = Answer(3,2,"穴=丸というイメージがあるから")
answ11 = Answer(3,1,"製造コストが安いから")
answ12 = Answer(3,3,"雨水がたまらないように")
answ13 = Answer(4,1,"泣いてお願いする")
answ14 = Answer(4,3,"ペンの長所を話す")
answ15 = Answer(4,2,"精神論を語る")
answ16 = Answer(4,4,"買わない理由を詰める")
answ17 = Answer(5,3,"貯金する")
answ18 = Answer(5,4,"勉強する")
answ19 = Answer(5,2,"遊ぶ")
answ20 = Answer(5,1,"競馬に行く")
answ21 = Answer(6,1,"酒池肉林")
answ22 = Answer(6,4,"一生懸命")
answ23 = Answer(6,3,"泰然自若")
answ24 = Answer(6,2,"以心伝心")

db_session.add(answ1)
db_session.add(answ2)
db_session.add(answ3)
db_session.add(answ4)
db_session.add(answ5)
db_session.add(answ6)
db_session.add(answ7)
db_session.add(answ8)
db_session.add(answ9)
db_session.add(answ10)
db_session.add(answ11)
db_session.add(answ12)
db_session.add(answ13)
db_session.add(answ14)
db_session.add(answ15)
db_session.add(answ16)
db_session.add(answ17)
db_session.add(answ18)
db_session.add(answ19)
db_session.add(answ20)
db_session.add(answ21)
db_session.add(answ22)
db_session.add(answ23)
db_session.add(answ24)
db_session.commit()