from database.init_database import db_session
from database.models import Answer

def insert_answers():
    answer1  = Answer(1,"バイト")
    answer2  = Answer(1,"勉強")
    answer3  = Answer(1,"株")
    answer4  = Answer(1,"趣味")
    answer5  = Answer(2,"安定性を求めたから")
    answer6  = Answer(2,"どこにも受からなかったから")
    answer7  = Answer(2,"自分が成長できる環境だと思ったから")
    answer8  = Answer(2,"経営理念に惹かれたから")
    answer9  = Answer(3,"蓋が落ちないように")
    answer10 = Answer(3,"穴=丸というイメージがあるから")
    answer11 = Answer(3,"製造コストが安いから")
    answer12 = Answer(3,"雨水がたまらないように")
    answer13 = Answer(4,"泣いてお願いする")
    answer14 = Answer(4,"ペンの長所を話す")
    answer15 = Answer(4,"精神論を語る")
    answer16 = Answer(4,"買わない理由を詰める")
    answer17 = Answer(5,"貯金する")
    answer18 = Answer(5,"勉強する")
    answer19 = Answer(5,"遊ぶ")
    answer20 = Answer(5,"競馬に行く")
    answer21 = Answer(6,"酒池肉林")
    answer22 = Answer(6,"一生懸命")
    answer23 = Answer(6,"泰然自若")
    answer24 = Answer(6,"以心伝心")

    db_session.add(answer1)
    db_session.add(answer2)
    db_session.add(answer3)
    db_session.add(answer4)
    db_session.add(answer5)
    db_session.add(answer6)
    db_session.add(answer7)
    db_session.add(answer8)
    db_session.add(answer9)
    db_session.add(answer10)
    db_session.add(answer11)
    db_session.add(answer12)
    db_session.add(answer13)
    db_session.add(answer14)
    db_session.add(answer15)
    db_session.add(answer16)
    db_session.add(answer17)
    db_session.add(answer18)
    db_session.add(answer19)
    db_session.add(answer20)
    db_session.add(answer21)
    db_session.add(answer22)
    db_session.add(answer23)
    db_session.add(answer24)
    db_session.commit()